# Generated by Django 5.2.3 on 2025-06-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Pega el enlace directo (https://…jpg, .png, etc.)', null=True),
        ),
    ]
